import pytest
import os
from unittest.mock import patch
from collections import namedtuple
from suse_migration_services.resolv_conf import ResolvConf
from suse_migration_services.command import Command

NETCONFIG_CONTENT = """### /etc/resolv.conf file autogenerated by netconfig!
#
# Before you change this file manually, consider to define the
# static DNS configuration using the following variables in the
# /etc/sysconfig/network/config file:
#     NETCONFIG_DNS_STATIC_SEARCHLIST
#     NETCONFIG_DNS_STATIC_SERVERS
#     NETCONFIG_DNS_FORWARDER
# or disable DNS configuration updates via netconfig by setting:
#     NETCONFIG_DNS_POLICY=''
#
# See also the netconfig(8) manual page and other documentation.
#
# Note: Manual change of this file disables netconfig too, but
# may get lost when this file contains comments or empty lines
# only, the netconfig settings are same with settings in this
# file and in case of a "netconfig update -f" call.
#
### Please remove (at least) this line when you modify the file!
search opensuse.org
nameserver 192.168.122.1
"""
NETCONFIG_MD5 = """#^###
92a4bf9ea461d072ee9a67a929e95916  -
"""

NM_CONTENT = """# Generated by NetworkManager
search nm.de
nameserver 8.8.8.8
"""

CUSTOM_CONTENT = "nameserver 1.1.1.1\n"

LINK_NAME = ''


class TestResolveConf:
    @pytest.fixture
    def setup_env(self, tmp_path):
        target_root = tmp_path / "system-root"

        dest_dir = tmp_path
        (target_root / 'etc').mkdir(parents=True)
        (dest_dir / 'etc').mkdir(parents=True)
        original_run = Command.run
        with patch(
                'suse_migration_services.resolv_conf.Defaults.get_system_root_path',
                return_value=str(target_root)
        ):
            with patch.object(Command, 'run') as mock_command_run:
                def side_effect(command, custom_env=None, raise_on_error=True):
                    command_type = namedtuple('command', ['output', 'error', 'returncode'])
                    if len(command) > 0 and command[0] == 'chroot':
                        return command_type(output=LINK_NAME, error='', returncode=0)
                    return original_run(command, custom_env, raise_on_error)

                mock_command_run.side_effect = side_effect
                yield target_root, dest_dir

    def test_nm_generated(self, setup_env):
        target_root, dest_dir = setup_env
        resolv_file = target_root / "etc/resolv.conf"
        resolv_file.write_text(NM_CONTENT)

        rc = ResolvConf()
        rc.setup_target_root()

        assert (target_root / "etc/resolv.conf").exists()
        assert not os.path.islink(target_root / "etc/resolv.conf")

    def test_nm_generated_live(self, setup_env):
        target_root, dest_dir = setup_env
        resolv_file = target_root / "etc/resolv.conf"
        resolv_file.write_text(NM_CONTENT)

        rc = ResolvConf()
        rc.setup_live_system(dest_dir)

        assert not (dest_dir / "etc/resolv.conf").exists()
        assert (target_root / "etc/resolv.conf").exists()

    def test_netconfig_match(self, setup_env):
        target_root, dest_dir = setup_env
        resolv_file = target_root / "etc/resolv.conf"
        resolv_file.write_text(NETCONFIG_CONTENT)

        md5_path = target_root / "var/adm/netconfig/md5/etc/resolv.conf"
        md5_path.parent.mkdir(parents=True, exist_ok=True)
        md5_path.write_text(NETCONFIG_MD5)

        rc = ResolvConf()
        rc.setup_target_root()

        assert (target_root / "etc/resolv.conf").exists()
        assert not os.path.islink(target_root / "etc/resolv.conf")

    def test_netconfig_match_live(self, setup_env):
        target_root, dest_dir = setup_env
        resolv_file = target_root / "etc/resolv.conf"
        resolv_file.write_text(NETCONFIG_CONTENT)

        md5_path = target_root / "var/adm/netconfig/md5/etc/resolv.conf"
        md5_path.parent.mkdir(parents=True, exist_ok=True)
        md5_path.write_text(NETCONFIG_MD5)

        rc = ResolvConf()
        rc.setup_live_system(dest_dir)

        assert not (dest_dir / "etc/resolv.conf").exists()

    def test_netconfig_mismatch(self, setup_env):
        target_root, dest_dir = setup_env
        resolv_file = target_root / "etc/resolv.conf"
        resolv_file.write_text(NETCONFIG_CONTENT.replace("opensuse.org", "suse.com"))

        md5_path = target_root / "var/adm/netconfig/md5/etc/resolv.conf"
        md5_path.parent.mkdir(parents=True, exist_ok=True)
        md5_path.write_text(NETCONFIG_MD5)

        rc = ResolvConf()
        rc.setup_target_root()

        assert (target_root / "etc/resolv.conf.static").exists()
        assert (target_root / "etc/resolv.conf").is_symlink()

    def test_netconfig_mismatch_live(self, setup_env):
        target_root, dest_dir = setup_env
        resolv_file = target_root / "etc/resolv.conf"
        resolv_file.write_text(NETCONFIG_CONTENT.replace("opensuse.org", "suse.com"))

        md5_path = target_root / "var/adm/netconfig/md5/etc/resolv.conf"
        md5_path.parent.mkdir(parents=True, exist_ok=True)
        md5_path.write_text(NETCONFIG_MD5)

        rc = ResolvConf()
        rc.setup_live_system(dest_dir)

        assert (dest_dir / "etc/resolv.conf.static").exists()
        assert (dest_dir / "etc/resolv.conf").is_symlink()

    def test_custom_content(self, setup_env):
        target_root, dest_dir = setup_env
        resolv_file = target_root / "etc/resolv.conf"
        resolv_file.write_text(CUSTOM_CONTENT)

        rc = ResolvConf()
        rc.setup_target_root()

        assert (target_root / "etc/resolv.conf.static").read_text() == CUSTOM_CONTENT
        assert os.path.islink(target_root / "etc/resolv.conf")

    def test_custom_content_live(self, setup_env):
        target_root, dest_dir = setup_env
        resolv_file = target_root / "etc/resolv.conf"
        resolv_file.write_text(CUSTOM_CONTENT)

        rc = ResolvConf()
        rc.setup_live_system(dest_dir)

        assert (dest_dir / "etc/resolv.conf.static").read_text() == CUSTOM_CONTENT
        assert os.path.islink(dest_dir / "etc/resolv.conf")

    def test_custom_link(self, setup_env):
        global LINK_NAME
        target_root, dest_dir = setup_env
        LINK_NAME = '/etc/resolv.conf.custom'
        target_link = target_root / "etc/resolv.conf"

        os.symlink("/etc/resolv.conf.custom", target_link)
        custom_path = target_root / "etc/resolv.conf.custom"
        custom_path.write_text(CUSTOM_CONTENT)

        rc = ResolvConf()
        rc.setup_target_root()

        assert os.readlink(target_link) == LINK_NAME

    def test_custom_link_live(self, setup_env):
        global LINK_NAME
        target_root, dest_dir = setup_env
        LINK_NAME = '/etc/resolv.conf.custom'
        target_link = target_root / "etc/resolv.conf"

        os.symlink("/etc/resolv.conf.custom", target_link)
        custom_path = target_root / "etc/resolv.conf.custom"
        custom_path.write_text(CUSTOM_CONTENT)

        rc = ResolvConf()
        rc.setup_live_system(dest_dir)

        assert (dest_dir / 'etc/resolv.conf').is_symlink()
        assert (dest_dir / 'etc/resolv.conf.static').exists()
        assert (dest_dir / 'etc/resolv.conf').read_text() == CUSTOM_CONTENT

    def test_nm_link(self, setup_env):
        global LINK_NAME
        target_root, dest_dir = setup_env
        LINK_NAME = '/run/NetworkManager/resolv.conf'
        target_link = target_root / "etc/resolv.conf"
        os.symlink(LINK_NAME, target_link)

        assert target_link.is_symlink()

        rc = ResolvConf()
        rc.setup_target_root()

        assert not target_link.is_symlink()

    def test_nm_link_live(self, setup_env):
        global LINK_NAME
        target_root, dest_dir = setup_env
        LINK_NAME = '/run/NetworkManager/resolv.conf'
        target_link = target_root / "etc/resolv.conf"

        os.symlink(LINK_NAME, target_link)

        assert target_link.is_symlink()

        rc = ResolvConf()
        rc.setup_live_system(dest_dir)

        assert not (dest_dir / 'etc/resolv.conf').is_symlink()
        assert target_link.is_symlink()

    def test_netconfig_link(self, setup_env):
        global LINK_NAME
        target_root, dest_dir = setup_env
        LINK_NAME = '/run/netconfig/resolv.conf'
        target_link = target_root / "etc/resolv.conf"
        os.symlink(LINK_NAME, target_link)

        assert target_link.is_symlink()

        rc = ResolvConf()
        rc.setup_target_root()

        assert not target_link.is_symlink()

    def test_netconfig_link_live(self, setup_env):
        global LINK_NAME
        target_root, dest_dir = setup_env
        LINK_NAME = '/run/netconfig/resolv.conf'
        target_link = target_root / "etc/resolv.conf"

        os.symlink(LINK_NAME, target_link)

        assert target_link.is_symlink()

        rc = ResolvConf()
        rc.setup_live_system(dest_dir)

        assert not (dest_dir / 'etc/resolv.conf').is_symlink()
        assert target_link.is_symlink()

    def test_existing_static_live(self, setup_env):
        target_root, dest_dir = setup_env
        resolv_src = target_root / "etc/resolv.conf"
        resolv_src.write_text(CUSTOM_CONTENT)

        static_file = dest_dir / "etc/resolv.conf.static"
        static_file.write_text("old content")

        rc = ResolvConf()
        rc.setup_live_system(dest_dir)

        # resolv.conf (link) -> resolv.conf.static-TIMESTAMP
        link_target = os.readlink(str(dest_dir / "etc/resolv.conf"))
        assert link_target.startswith("resolv.conf.static-")
        assert (dest_dir / 'etc' / link_target).read_text() == CUSTOM_CONTENT
        assert static_file.read_text() == "old content"

    def test_invalid_link_live(self, setup_env):
        global LINK_NAME
        target_root, dest_dir = setup_env
        LINK_NAME = ''
        target_link = target_root / "etc/resolv.conf"
        os.symlink('I DO NOT EXISTS', target_link)

        rc = ResolvConf()
        rc.setup_live_system(dest_dir)
        rc.setup_target_root()

        assert not (dest_dir / 'etc/resolv.conf').is_symlink()
        assert (target_root / 'etc/resolv.conf').is_symlink()

    def test_link_target_does_not_exists_live(self, setup_env):
        global LINK_NAME
        target_root, dest_dir = setup_env
        LINK_NAME = '/I/Do/not/exists/resolv.conf'
        target_link = target_root / "etc/resolv.conf"
        os.symlink(LINK_NAME, target_link)

        rc = ResolvConf()
        rc.setup_live_system(dest_dir)

        assert not (dest_dir / 'etc/resolv.conf').is_symlink()

    def test_generated_netconfig_md5_not_exists(self, setup_env):
        rc = ResolvConf()
        assert rc.generate_netconfig_md5('IdoNotExists.conf', '^###') is None
