import pytest
import os
from suse_migration_services.resolv_conf import ResolvConf

NETCONFIG_CONTENT = """### /etc/resolv.conf file autogenerated by netconfig!
#
# Before you change this file manually, consider to define the
# static DNS configuration using the following variables in the
# /etc/sysconfig/network/config file:
#     NETCONFIG_DNS_STATIC_SEARCHLIST
#     NETCONFIG_DNS_STATIC_SERVERS
#     NETCONFIG_DNS_FORWARDER
# or disable DNS configuration updates via netconfig by setting:
#     NETCONFIG_DNS_POLICY=''
#
# See also the netconfig(8) manual page and other documentation.
#
# Note: Manual change of this file disables netconfig too, but
# may get lost when this file contains comments or empty lines
# only, the netconfig settings are same with settings in this
# file and in case of a "netconfig update -f" call.
#
### Please remove (at least) this line when you modify the file!
search opensuse.org
nameserver 192.168.122.1
"""
NETCONFIG_MD5 = "92a4bf9ea461d072ee9a67a929e95916"
ERX = "^###"

NM_CONTENT = """# Generated by NetworkManager
search nm.de
nameserver 8.8.8.8
"""

CUSTOM_CONTENT = "nameserver 1.1.1.1\n"


class TestResolveConf:
    @pytest.fixture
    def setup_env(self, tmp_path):
        target_root = tmp_path / "system-root"
        target_root.mkdir()

        src_dir = target_root / "etc"
        dest_dir = tmp_path / "etc"

        src_dir.mkdir()
        dest_dir.mkdir()

        return target_root, src_dir, dest_dir

    def test_nm_generated(self, setup_env):
        target_root, src_dir, dest_dir = setup_env
        resolv_file = src_dir / "resolv.conf"
        resolv_file.write_text(NM_CONTENT)

        rc = ResolvConf(str(target_root), str(src_dir), str(dest_dir))
        rc.prepare_resolv_conf()

        assert not (dest_dir / "resolv.conf").exists()

    def test_netconfig_match(self, setup_env):
        target_root, src_dir, dest_dir = setup_env
        resolv_file = src_dir / "resolv.conf"
        resolv_file.write_text(NETCONFIG_CONTENT)

        md5_path = target_root / "var/adm/netconfig/md5/etc/resolv.conf"
        md5_path.parent.mkdir(parents=True, exist_ok=True)
        md5_path.write_text(f"#{ERX}\n{NETCONFIG_MD5}  -\n")

        rc = ResolvConf(str(target_root), str(src_dir), str(dest_dir))
        rc.prepare_resolv_conf()

        assert not (dest_dir / "resolv.conf").exists()

    def test_netconfig_mismatch(self, setup_env):
        target_root, src_dir, dest_dir = setup_env
        resolv_file = src_dir / "resolv.conf"
        resolv_file.write_text(NETCONFIG_CONTENT.replace("opensuse.org", "suse.com"))

        md5_path = target_root / "var/adm/netconfig/md5/etc/resolv.conf"
        md5_path.parent.mkdir(parents=True, exist_ok=True)
        md5_path.write_text(f"#{ERX}\n{NETCONFIG_MD5}  -\n")

        rc = ResolvConf(str(target_root), str(src_dir), str(dest_dir))
        rc.prepare_resolv_conf()

        assert (dest_dir / "resolv.conf.static").exists()
        assert (dest_dir / "resolv.conf").is_symlink()

    def test_custom_content(self, setup_env):
        target_root, src_dir, dest_dir = setup_env
        resolv_file = src_dir / "resolv.conf"
        resolv_file.write_text(CUSTOM_CONTENT)

        rc = ResolvConf(str(target_root), str(src_dir), str(dest_dir))
        rc.prepare_resolv_conf()

        assert (dest_dir / "resolv.conf.static").read_text() == CUSTOM_CONTENT

    def test_nm_link(self, setup_env):
        target_root, src_dir, dest_dir = setup_env
        os.symlink("/run/NetworkManager/resolv.conf", str(src_dir / "resolv.conf"))
        nm_path = target_root / "run/NetworkManager/resolv.conf"
        nm_path.parent.mkdir(parents=True, exist_ok=True)
        nm_path.write_text(NM_CONTENT)

        dest_link = dest_dir / "resolv.conf"
        os.symlink("dummy", str(dest_link))

        rc = ResolvConf(str(target_root), str(src_dir), str(dest_dir))
        rc.prepare_resolv_conf()

        assert not dest_link.exists()
        assert not dest_link.is_symlink()

    def test_netconfig_link(self, setup_env):
        target_root, src_dir, dest_dir = setup_env
        os.symlink("/run/netconfig/resolv.conf", str(src_dir / "resolv.conf"))
        nc_path = target_root / "run/netconfig/resolv.conf"
        nc_path.parent.mkdir(parents=True, exist_ok=True)
        nc_path.write_text(NETCONFIG_CONTENT)

        md5_path = target_root / "var/adm/netconfig/md5/etc/resolv.conf"
        md5_path.parent.mkdir(parents=True, exist_ok=True)
        md5_path.write_text(f"#{ERX}\n{NETCONFIG_MD5}  -\n")

        dest_link = dest_dir / "resolv.conf"
        os.symlink("dummy", str(dest_link))

        rc = ResolvConf(str(target_root), str(src_dir), str(dest_dir))
        rc.prepare_resolv_conf()

        assert not dest_link.exists()

    def test_custom_link(self, setup_env):
        target_root, src_dir, dest_dir = setup_env
        os.symlink("/etc/resolv.conf.custom", str(src_dir / "resolv.conf"))
        custom_path = target_root / "etc/resolv.conf.custom"
        custom_path.parent.mkdir(parents=True, exist_ok=True)
        custom_path.write_text(CUSTOM_CONTENT)

        rc = ResolvConf(str(target_root), str(src_dir), str(dest_dir))
        rc.prepare_resolv_conf()

        assert (dest_dir / "resolv.conf.static").read_text() == CUSTOM_CONTENT

    def test_chained_links(self, setup_env):
        target_root, src_dir, dest_dir = setup_env
        # resolv.conf -> resolv.link -> /etc/real
        os.symlink("resolv.link", str(src_dir / "resolv.conf"))
        os.symlink("/etc/real", str(src_dir / "resolv.link"))

        real_path = target_root / "etc/real"
        real_path.parent.mkdir(parents=True, exist_ok=True)
        real_path.write_text(CUSTOM_CONTENT)

        rc = ResolvConf(str(target_root), str(src_dir), str(dest_dir))
        rc.prepare_resolv_conf()

        assert (dest_dir / "resolv.conf.static").read_text() == CUSTOM_CONTENT

    def test_breakout_link(self, setup_env):
        target_root, src_dir, dest_dir = setup_env
        os.symlink("../../../etc/shadow", str(src_dir / "resolv.conf"))

        rc = ResolvConf(str(target_root), str(src_dir), str(dest_dir))
        rc.prepare_resolv_conf()
        assert not (dest_dir / "resolv.conf").exists()

    def test_broken_link(self, setup_env):
        target_root, src_dir, dest_dir = setup_env
        os.symlink("nonexistent", str(src_dir / "resolv.conf"))

        rc = ResolvConf(str(target_root), str(src_dir), str(dest_dir))
        rc.prepare_resolv_conf()
        assert not (dest_dir / "resolv.conf").exists()

    def test_existing_static(self, setup_env):
        target_root, src_dir, dest_dir = setup_env
        resolv_src = src_dir / "resolv.conf"
        resolv_src.write_text(CUSTOM_CONTENT)

        static_file = dest_dir / "resolv.conf.static"
        static_file.write_text("old content")

        rc = ResolvConf(str(target_root), str(src_dir), str(dest_dir))
        rc.prepare_resolv_conf()

        # resolv.conf (link) -> resolv.conf.static-TIMESTAMP
        link_target = os.readlink(str(dest_dir / "resolv.conf"))
        assert link_target.startswith("resolv.conf.static-")
        assert (dest_dir / link_target).read_text() == CUSTOM_CONTENT
        # old resolv.conf.static should still have 'old content'
        assert static_file.read_text() == "old content"

    def test_read_netconfig_md5_invalid_format(self, setup_env):
        target_root, src_dir, dest_dir = setup_env
        md5_path = target_root / "var/adm/netconfig/md5/etc/resolv.conf"
        md5_path.parent.mkdir(parents=True, exist_ok=True)
        md5_path.write_text("invalid format\n")

        rc = ResolvConf(str(target_root), str(src_dir))
        assert rc.read_netconfig_md5() == (None, None)

    def test_create_netconfig_md5_edge_cases(self, setup_env):
        target_root, src_dir, dest_dir = setup_env
        rc = ResolvConf(str(target_root), str(src_dir))
        assert rc.create_netconfig_md5("nonexistent", "^###") is None
        assert rc.create_netconfig_md5(str(src_dir), None) is None

    def test_is_custom_resolv_conf_not_exists(self, setup_env):
        target_root, src_dir, dest_dir = setup_env
        rc = ResolvConf(str(target_root), str(src_dir))
        assert rc.is_custom_resolv_conf("nonexistent") is False

    def test_resolve_chroot_symlink_not_a_link(self, setup_env):
        target_root, src_dir, dest_dir = setup_env
        file_path = src_dir / "file"
        file_path.write_text("data")
        rc = ResolvConf(str(target_root), str(src_dir))
        with pytest.raises(ValueError, match="is not a valid symlink"):
            rc.resolve_chroot_symlink(str(file_path), str(target_root))

    def test_prepare_resolv_conf_link_same_dir(self, setup_env):
        target_root, src_dir, dest_dir = setup_env
        rc = ResolvConf(str(target_root), str(src_dir), str(src_dir))
        os.symlink("real_target", str(src_dir / "resolv.conf"))
        (src_dir / "real_target").write_text(CUSTOM_CONTENT)
        rc.prepare_resolv_conf()
        assert os.path.islink(str(src_dir / "resolv.conf"))
        assert not (src_dir / "resolv.conf.static").exists()

    def test_copy_logic(self, setup_env):
        target_root, src_dir, dest_dir = setup_env
        rc = ResolvConf(str(target_root), str(src_dir))

        src_file = src_dir / "src"
        src_file.write_text("data")
        dst_file = dest_dir / "dst"

        # Test copy same file returns early
        rc.copy(str(src_file), str(src_file))

        # Test copy over existing link unlinks first (line 77)
        os.symlink("dummy", str(dst_file))
        rc.copy(str(src_file), str(dst_file))
        assert not os.path.islink(str(dst_file))
        assert dst_file.read_text() == "data"

    def test_is_custom_resolv_conf_fallback_no_nameserver(self, setup_env):
        target_root, src_dir, dest_dir = setup_env
        resolv_file = src_dir / "resolv.conf"
        resolv_file.write_text("just a comment\n")
        rc = ResolvConf(str(target_root), str(src_dir))
        assert rc.is_custom_resolv_conf(str(resolv_file)) is False
